import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>khanguslee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={'w-screen h-screen flex flex-col justify-center'}>
        <h1
          className={
            'text-dracula-green text-center md:text-8xl sm:text-6xl text-4xl font-medium'
          }
        >
          khanguslee
        </h1>
      </div>
    </>
  );
}
